version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
before_build:
- cmd: msbuild /t:Restore
build:
  project: Mono.TextTemplating.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: packages\**\*.nupkg
