// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Mono.TextTemplating;

/// <summary>
/// Controls what code is generated by the template.
/// Internal for now, until we have a better idea of what the API should look like.
/// </summary>
class CodeGenerationOptions
{
	/// <summary>
	/// Whether to use System.Runtime.Remoting.Messaging.CallContext
	/// </summary>
	public bool UseRemotingCallContext { get; set; }
}
